cc_library(
    name = "utils_lib",
    srcs = [
        "helper.c",
        "pretty.c",
    ],
    hdrs = [
        "helper.h",
        "pretty.h",
    ],
    includes = ["."],
    visibility = ["//visibility:public"],
)