name: Linux Dev Build

on:
  push:
    branches:
      - feature/**
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install GCC + Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-11 g++-11 
          sudo apt-get install libxml2 libxml2-dev
          sudo apt-get install bazel
      
      - name: Build
        run: bazel build //main:cart 
