name: Linux Dev Build

on:
  push:
    branches:
      - feature/**
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install GCC + Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-11 g++-11 
          sudo apt-get install libxml2 libxml2-dev
      
      - name: Install bazel
        run: |
          sudo apt install apt-transport-https curl gnupg -y
          curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg
          sudo mv bazel-archive-keyring.gpg /usr/share/keyrings
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
          sudo apt update && sudo apt install bazel

      - name: Build
        run: bazel build //main:cart 
